Needs GHC >= 7.10 due to Prelude.(<$>)
```
src/Profiteur/Core.hs:75:30:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<>’ (imported from Data.Monoid)
```